# -*- coding: utf-8 -*-
"""Prediksi berat badan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12weq1gXpm49qDWHAU94A5BpU-qkXpjKs
"""

import pandas as pd
import numpy as np
import seaborn as sns
sns.set_theme(style="darkgrid")
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import pickle
from joblib import dump

data=pd.read_csv('weight-height.csv')
data.head()

data['Gender'].replace(['Male','Female'],[0,1],inplace=True)

data

data.shape

plt.scatter(data['Weight'],data['Height'])

labler= LabelEncoder()
# scaledData=scaler.fit_transform(data)
# scaledx=scaler.fit_transform(data2)
# scaledData

data.Gender=labler.fit_transform(data.Gender)

x = data[['Gender','Height']]
y = data.iloc[:, 2:3]
x

x.dtypes

y

"""#Split & train"""

xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=905)

reg= LinearRegression()

fitReg=reg.fit(xtrain,ytrain)

yPred=reg.predict(xtest)
xtest

xtrain

yPred

plt.scatter(xtest, ytest)
plt.plot(xtrain,reg.predict(xtrain),color='r')
plt.xlabel('Height')
plt.ylabel('Weight')

print(f"Model Accuracy is: {reg.score(xtest, ytest)}")

r2_score(ytest,yPred)

dump((fitReg),filename='model.pkl')